### ISSUE TITLE
Provide IECC Climate Zone for each IECC Year

### ISSUE THREAD

**Issue by OneGeek** [openeemeter/eeweather#22]
This could be very useful if it could look up both the 2006 and 2009 IECC climate zones for a location. I am about 80% sure those are the only years where the zones changed and that 2012 and 2015 have not changed them.

**Comment by philngo** [comment]
Thanks for the suggestion. What is your use case? That seems like something that could be added in the future if there was enough demand for it. If you could point to reference material showing the differences in the boundaries that would be helpful.

**Comment by OneGeek** [comment]
I'm working with @shorowit as he develops the [ERI use-case](https://github.com/NREL/OpenStudio-ERI) for the [HPXML standard](http://www.hpxmlonline.com/) for the purpose of improving the consistency of ERI and related home energy ratings, e.g. HERS, across different software. A recent discussion brought to light that the various software that would make use of the calculation engine may not be consistent in terms of what climate zone they consider a given location to have, and that there was no readily available machine consumable source-of-truth for the IECC climate zone for any particular IECC year. In looking for a solution I came across your work.

The canonical, to the best of my knowledge, IECC climate zone documents are available through the ICC's site.

 * [2006 IECC](https://codes.iccsafe.org/public/public/chapter/content/4272/) (direct link to climate zones listing (embedded as pdf))
 * [2009 IECC](https://codes.iccsafe.org/public/public/chapter/content/4716/) (direct link to climate zones listing (embedded as pdf))
 * [2012 IECC](https://codes.iccsafe.org/public/document/IECC2012/chapter-3-ce-general-requirements) (direct link to climate zones listing)
 * [2015 IECC](https://codes.iccsafe.org/public/document/IECC2015/chapter-3-ce-general-requirements) (direct link to climate zones listing)

**Comment by philngo** [comment]
Thank you! Very very helpful. I'll leave this issue open since I probably won't get started on it right away. I don't love PDFs as a source of truth and previously had made this CSV (below) by manually copying out the list. We had previously found errors (human mistakes) in it but aren't aware of any now.  This CSV is what eeweather bases its IECC climate zone handling on. At the time when I was working on developing this, I didn't realize there were multiple versions of the standard (obvious in hindsight - especially as even county names upon which this is based change from time to time), or I might have been more specific in indicating which version(s) the eeweather package uses.

If or when we do get started on this process, the first step will be to get those county/climate zone lists into this CSV. If this is an urgent matter for you, you could hasten the process by forking and adding new columns to this CSV containing the appropriate data and we can go from there.

https://gist.github.com/philngo/d3e251040569dba67942

**Comment by philngo** [comment]
This doesn't seem to be a high priority so I am closing this issue. If anyone interested in this makes progress on this issue, please feel free to reopen this issue to continue the discussion or (preferred) open a pull request with a proposed implementation.
