### ISSUE TITLE
Receiving an exception when trying to pull ISD temperature data

### ISSUE THREAD

**Issue by amrutatkulkarni** [openeemeter/eeweather#62]
**Describe the bug**
Calls to the method to pull ISD temperature data raise an exception

**To Reproduce**
1. call .load_isd_hourly_temp_data() on a station.
Exception encountered: Could not connect to ftp.ncdc.noaa.gov.

**Expected behavior**
Normally returns data from NOAA or returns an expected error code.

**Comment by philngo** [comment]
This will sometimes happen if the NOAA ftp is down, or if the network you are using either down or the firewall does not allow requests to the ftp site. The NOAA ftp seems to be up currently, so you might consider trying again. The following script works for me as expected:

```
import eeweather
from datetime import datetime
import pytz
station = eeweather.ISDStation("722880")
start = datetime(2012, 1, 1, tzinfo=pytz.UTC)
end = datetime(2013, 1, 1, tzinfo=pytz.UTC)
station.load_isd_hourly_temp_data(start, end)
```

**Comment by UGuntupalli** [comment]
@philngo, 
           When I try to take your sample code and run it, I keep running into a different error. Does eeweather require sqlalchemy in the environment ? Or is it hinting at something else ? If yes, does it not install the dependency during pip install ? 

```python 
   "KeyValueStore requires sqlalchemy" 
```

**Comment by philngo** [comment]
@UGuntupalli In the short term, if you pip install sqlalchemy into your development environment that will fix the issue. I'm going to close this issue because it's on a different and resolved topic, but please feel free to reopen a new issue if that doesn't work out. On the longer term side, please also open a separate issue if you think we should include `sqlalchemy` in the setup.py requirements. This will need to be a discussion. for now we have not included it because there are parts of the library that are useful without it, and we want to give users more granular control over their environments.
